### PR TITLE
#101 add new blog

### PR DESCRIPTION
**Pull request by fabusuyi-deborah**
My first draft submission for issue #101that is titled "JavaScript Essentials: Understanding Variables and Data Types".

### CODE REVIEW

**Comment by fabusuyi-deborah** [comment]
Thanks for the feedback @Aahil13, I'll implement them. I'll let you know if I have any questions.

**Comment by fabusuyi-deborah** [comment]
Hi @Aahil13, Thanks once again for the feedback.  I implemented them and I'm open to more feedback. Thanks.

**Review by Aahil13 — APPROVED** [review]
Wonderful!

Made some minor changes, but everything looks good now. Can't wait to see your next piece.

**Comment by Aahil13** [comment]
Hey @fabusuyi-deborah I've approved this, but I'll need you to make one small change to this file. Make sure the file is saved with a `.md` extension. Make that change and open a new PR

**Comment by fabusuyi-deborah** [comment]
Hey @Aahil1, Thanks for making my first article contribution to Open source simple and easy. I'd make the change and open a new PR. I can't wait for my next contribution.

**Pull request merged**
